name: Docker publish

on:
  workflow_dispatch:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    # branches:
    #   - $default-branch

    # Publish `v1.2.3` tags as releases.
    tags:
    #   - v*
      - '*'
      
  # Run tests for any PRs.
  pull_request:

#env:
  # TODO: Change variable to your image's name.
#  IMAGE_NAME: image

jobs:  # workflow中的job

  push_to_registry:  # job的名字
    name: Push Docker image to Docker Hub
    runs-on: servercore:ltsc2019   # job运行的基础环境

    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4  # 抽取项目信息，主要是镜像的tag
        with:
          images: slzlzxlz/devservercore

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # docker build & push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
